name: Karate DSL Tests
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
    
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: target/*.jar
          if-no-files-found: warn

  karate-test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: target/

      - name: Run Application
        run: |
          java -jar target/*.jar &
          until curl --silent --fail http://localhost:8080/api/health; do
            echo "Waiting for application to be healthy..."
            sleep 5
          done

      - name: Run Karate DSL Tests
        run: mvn clean test -Dtest=ApiTest

      - name: Upload Cucumber HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: target/cucumber-html-reports/
          if-no-files-found: warn
