name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
    
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Spring Boot Application
        run: mvn spring-boot:run

      - name: Run Unit Tests
        run: mvn clean test

      - name: Run Karate DSL Tests
        run: mvn clean test -Dtest=ApiTest

      - name: Upload Cucumber HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: target/cucumber-html-reports/
          if-no-files-found: warn